version: '3.8'

services:
  phishing-detector:
    build: .
    container_name: phishing-detector-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/best_model.pth
      - CONFIG_PATH=/app/models/model_config.json
      - PYTHONUNBUFFERED=1
    volumes:
      # Monter les modèles depuis l'hôte (optionnel)
      - ./models:/app/models:ro
      # Monter les logs pour persistance
      - ./logs:/app/logs
      # Monter les données de test (optionnel)
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # Service optionnel pour monitoring (Prometheus + Grafana)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'

networks:
  default:
    name: phishing-detector-network
